In [ ]:
Consider the below code to answer further questions:

In [4]:
import numpy as np

list_ = ['1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data types of the variables list_ and array_list. The list_ variable is a Python list containing strings, while the array_list variable is a NumPy array.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

In [7]:
array_list = np.array(object = list_, dtype = int)

In [ ]:
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list after specifying dtype=int when creating array_list. 

In [8]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:

In [9]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [10]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Shape
shape = num_array.shape

# (ii) Size
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [12]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
