<a href="https://colab.research.google.com/github/Tahaarthuna112/Learning-with-data-masters/blob/main/TensorFlow_Fundamentals_Assignment_Qs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Part 1: Theoretical Queltionk

In [ ]:
1) What are the different data structures used in Tensorflow?. Give some examples?

In [ ]:
In TensorFlow, various data structures are used to handle and manipulate data during the machine learning and deep learning workflow. These data structures are designed to efficiently represent, store, and process data, especially for large-scale computations like those required in deep learning models. Here are the key data structures used in TensorFlow:

### 1. **Tensors**:
   - **Tensors** are the core data structure in TensorFlow. They represent multi-dimensional arrays of numerical data and are the basic building blocks for computations in TensorFlow. A tensor can have any number of dimensions (0D, 1D, 2D, etc.), also known as its **rank**.
   - TensorFlow operations (or "ops") are applied to tensors, allowing for efficient computation on CPU or GPU.

   **Examples**:
   - **0D Tensor** (scalar): A single number.
     Example: `tf.constant(5)`
   - **1D Tensor** (vector): A one-dimensional array of numbers.
     Example: `tf.constant([1.0, 2.0, 3.0])`
   - **2D Tensor** (matrix): A two-dimensional array (like a table of numbers).
     Example: `tf.constant([[1, 2], [3, 4]])`
   - **3D Tensor**: A tensor with three dimensions, often used for image data.
     Example: `tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

### 2. **Variables**:
   - **Variables** are special tensors in TensorFlow that are used to store and update model parameters during training. Unlike constants, variables are mutable, meaning their values can be changed during the execution of a model.
   - Variables are typically used to store the weights and biases of a model and can be updated through backpropagation.

   **Examples**:
   - A trainable weight matrix:
     ```python
     weight = tf.Variable(tf.random.normal([5, 5], stddev=0.1))
     ```

### 3. **Sparse Tensors**:
   - **Sparse tensors** represent tensors that contain mostly zero values, which helps optimize memory usage when working with large datasets that have a sparse representation. Instead of storing every element, sparse tensors store only the non-zero values and their corresponding indices.

   **Examples**:
   ```python
   sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
   ```

### 4. **Ragged Tensors**:
   - **Ragged tensors** are tensors with variable-length dimensions. They are used to handle data that doesn't fit into a regular grid, such as sequences of varying lengths (e.g., sentences in natural language processing or irregularly shaped images).

   **Examples**:
   - A batch of sentences with different lengths:
     ```python
     ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
     ```

### 5. **TensorArray**:
   - **TensorArray** is a dynamic array of tensors used in cases where the size of the array is not known in advance. It is useful in constructing loops and dynamic computation graphs in TensorFlow.

   **Examples**:
   - Creating a dynamic array to store intermediate results in a loop:
     ```python
     array = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
     ```

### 6. **Dataset**:
   - The **Dataset** API provides a flexible way to create and work with input data pipelines in TensorFlow. It is used to load and process large datasets in an efficient, scalable manner. Datasets can be created from data in memory (e.g., numpy arrays) or from files (e.g., images or text data).

   **Examples**:
   - Creating a dataset from a list of tensors:
     ```python
     dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
     ```

   - Creating a dataset from a CSV file:
     ```python
     dataset = tf.data.experimental.make_csv_dataset(file_pattern='data.csv', batch_size=32)
     ```

### 7. **Queues** (Deprecated in TensorFlow 2.x):
   - **Queues** were used in TensorFlow 1.x to manage input pipelines for batch processing. They were useful for prefetching and organizing data during training. However, in TensorFlow 2.x, queues have largely been replaced by the `tf.data` API.

   **Examples** (TensorFlow 1.x):
   ```python
   queue = tf.queue.FIFOQueue(capacity=10, dtypes=tf.float32)
   ```

### 8. **Lookup Tables**:
   - **Lookup tables** are used to map data from one domain to another, such as mapping words to indices in natural language processing tasks. They are often used to handle categorical data or embeddings in deep learning models.

   **Examples**:
   - Creating a lookup table for string to index mapping:
     ```python
     table = tf.lookup.StaticHashTable(
         initializer=tf.lookup.KeyValueTensorInitializer(
             keys=tf.constant(["apple", "banana"]),
             values=tf.constant([0, 1])
         ),
         default_value=-1
     )
     ```

### Summary:

- **Tensors**: Core data structure, representing n-dimensional arrays.
- **Variables**: Mutable tensors used to store model parameters.
- **Sparse Tensors**: Efficient representation of tensors with mostly zero values.
- **Ragged Tensors**: Handle data with variable-length dimensions.
- **TensorArray**: Dynamic array of tensors, useful in loops.
- **Dataset**: Efficient pipeline for loading and processing large datasets.
- **Lookup Tables**: Map data from one domain to another, useful for categorical data.

These data structures provide flexibility and efficiency in working with various types of data in TensorFlow, making it easier to build and train machine learning and deep learning models.

In [ ]:
2) How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example?

In [ ]:
In TensorFlow, both **constants** and **variables** are used to store data, but they have key differences in terms of mutability and their roles in model training.

### 1. **TensorFlow Constant (`tf.constant`)**:
   - **Immutability**: A **constant** in TensorFlow is immutable, meaning that once it is created, its value cannot be changed. Constants are typically used for fixed values that do not need to be updated during the model's lifecycle, such as static hyperparameters or input data that will remain the same.
   - **Use Case**: Constants are useful for scenarios where the data should remain unchanged, like the size of the input layer, or for passing values that are not modified during backpropagation in neural networks.

   **Example**:
   ```python
   import tensorflow as tf

   # Define a constant
   const_tensor = tf.constant([1, 2, 3, 4], dtype=tf.int32)

   print("Constant Tensor:", const_tensor)
   ```
   Output:
   ```
   Constant Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
   ```
   In this example, `const_tensor` holds a fixed array of integers, and its values cannot be modified after initialization.

### 2. **TensorFlow Variable (`tf.Variable`)**:
   - **Mutability**: A **variable** in TensorFlow is mutable, meaning its value can be changed during the execution of a model. Variables are primarily used for storing model parameters (like weights and biases) that are updated during the training process through backpropagation.
   - **Use Case**: Variables are critical in machine learning and deep learning models, where parameters need to be updated iteratively during training.

   **Example**:
   ```python
   import tensorflow as tf

   # Define a variable
   var_tensor = tf.Variable([1, 2, 3, 4], dtype=tf.int32)

   # Modify the variable's value
   var_tensor.assign([5, 6, 7, 8])

   print("Variable Tensor:", var_tensor)
   ```
   Output:
   ```
   Variable Tensor: <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>
   ```
   In this example, `var_tensor` initially holds the array `[1, 2, 3, 4]`, but its values are modified using the `assign()` method. This mutability is crucial during training, where model parameters are updated after each training step.

### Key Differences Between `tf.constant` and `tf.Variable`:
| Aspect              | `tf.constant`                          | `tf.Variable`                             |
|---------------------|----------------------------------------|-------------------------------------------|
| **Mutability**       | Immutable (values can't be changed)    | Mutable (values can be updated)           |
| **Typical Use**      | Fixed inputs like hyperparameters      | Model parameters like weights and biases  |
| **Backpropagation**  | Not trainable (unchanged during training) | Trainable (updated during backpropagation)|
| **Memory Management**| Memory allocated once                 | Memory updated as values change           |

### Use Case in Model Training:
- **Constants** are typically used for hyperparameters or fixed inputs (e.g., a constant learning rate).
- **Variables** are used to store model weights, which are updated as the training process optimizes the model to minimize the loss function.

### Example in a Simple Neural Network:
In a neural network, the **weights** and **biases** are initialized as **variables** because they are adjusted with each training iteration. On the other hand, something like the **learning rate** or the structure of the network may be stored as a **constant**, as it remains the same throughout the training process.

```python
# Defining weights as a variable (trainable)
weights = tf.Variable(tf.random.normal([2, 2]), name="weights")

# Defining learning rate as a constant (non-trainable)
learning_rate = tf.constant(0.01, dtype=tf.float32)
```

In summary, **constants** are used for fixed values, while **variables** store parameters that need to be updated during model training. Understanding their distinction is essential for building efficient models in TensorFlow.

In [ ]:
3) Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow?

In [ ]:
In TensorFlow, matrix operations such as addition, multiplication, and element-wise operations are fundamental for constructing and training machine learning and deep learning models. Here’s a detailed description of each operation along with examples.

### 1. **Matrix Addition**

Matrix addition involves adding two matrices of the same dimensions by adding their corresponding elements. The result is a new matrix of the same size.

**Mathematical Definition**:
If \( A \) and \( B \) are two matrices of the same shape, their sum \( C \) is defined as:
\[
C_{ij} = A_{ij} + B_{ij}
\]

**TensorFlow Example**:
```python
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
C = tf.add(A, B)

print("Matrix A:")
print(A.numpy())
print("Matrix B:")
print(B.numpy())
print("Matrix C (A + B):")
print(C.numpy())
```

**Output**:
```
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix C (A + B):
[[ 6  8]
 [10 12]]
```

### 2. **Matrix Multiplication**

Matrix multiplication involves multiplying two matrices, where the number of columns in the first matrix must equal the number of rows in the second matrix. The resulting matrix has the number of rows of the first matrix and the number of columns of the second matrix.

**Mathematical Definition**:
If \( A \) is an \( m \times n \) matrix and \( B \) is an \( n \times p \) matrix, the product \( C \) is given by:
\[
C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}
\]

**TensorFlow Example**:
```python
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
C = tf.matmul(A, B)

print("Matrix A:")
print(A.numpy())
print("Matrix B:")
print(B.numpy())
print("Matrix C (A * B):")
print(C.numpy())
```

**Output**:
```
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix C (A * B):
[[19 22]
 [43 50]]
```

### 3. **Element-wise Operations**

Element-wise operations perform operations on corresponding elements of two tensors (matrices or arrays) of the same shape. This includes addition, multiplication, and other arithmetic operations.

**Mathematical Definition**:
If \( A \) and \( B \) are two matrices of the same shape, their element-wise product \( C \) is defined as:
\[
C_{ij} = A_{ij} \cdot B_{ij}
\]

**TensorFlow Example for Element-wise Operations**:
```python
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Element-wise addition
C_add = tf.add(A, B)

# Element-wise multiplication
C_mul = tf.multiply(A, B)

print("Matrix A:")
print(A.numpy())
print("Matrix B:")
print(B.numpy())
print("Element-wise Addition (A + B):")
print(C_add.numpy())
print("Element-wise Multiplication (A * B):")
print(C_mul.numpy())
```

**Output**:
```
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Element-wise Addition (A + B):
[[ 6  8]
 [10 12]]
Element-wise Multiplication (A * B):
[[ 5 12]
 [21 32]]
```

### Summary of Operations

- **Matrix Addition**: Adds corresponding elements of two matrices of the same shape.
- **Matrix Multiplication**: Multiplies two matrices where the number of columns in the first matrix matches the number of rows in the second matrix.
- **Element-wise Operations**: Perform operations on corresponding elements of two tensors of the same shape, including addition, multiplication, and other arithmetic functions.

These operations are fundamental in TensorFlow and are extensively used in building neural networks, where matrix and tensor manipulations are commonplace.

In [ ]:
Part 2: Practical Implementation

Talk 1: Creating and Manipulating Matricek

In [ ]:
1) Create a normal matrix A with dimensions ²x², using TensorFlow's random_normal function. Display the
values of matrix A

In [ ]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
A = tf.random.normal(shape=(3, 3))

# Display the value of matrix A
print("Matrix A:")
print(A)

Matrix A:
tf.Tensor(
[[-0.10257177  0.63083196 -0.45404872]
 [-1.3704439  -0.30089492  1.4100798 ]
 [ 0.49787438 -0.5419311   1.0201961 ]], shape=(3, 3), dtype=float32)


In [ ]:
## Q2. Create a Gaussian Matrix B with dimension 4X4, using truncated_normal function. Display the values of Matrix B
---

In [ ]:
import tensorflow as tf

# Define the dimensions of the matrix
matrix_shape = (4, 4)

# Generate a Gaussian matrix using truncated normal distribution
mean = 0
stddev = 1
B = tf.random.truncated_normal(shape=matrix_shape, mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix B:")
print(B.numpy())

Matrix B:
[[-0.2085315  -0.16574441 -0.82045406 -1.0745512 ]
 [ 0.13144015 -1.3797266   1.1197685   0.6782506 ]
 [ 1.6350964   0.3484143  -0.29471496 -0.8506537 ]
 [ 0.7655658  -0.18303037  1.6271026  -0.6208647 ]]


In [ ]:
## Q3. Create a Gaussian Matrix C with dimension 2X2, where values are drawn from normal distribution with a mean of 3 and a standard deviation of 0.5, using Tensorflow's random.normal function Display values of matrix C.
---

In [ ]:
import tensorflow as tf

# Define the dimensions of the matrix
matrix_shape = (2, 2)

# Generate a Gaussian matrix using normal distribution
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=matrix_shape, mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix C:")
print(C.numpy())

Matrix C:
[[3.6540046 3.1320784]
 [3.3171096 2.8479006]]


In [ ]:
## Q4. Perform matrix addition between matrix A and matrix B and store the results in matrix D

In [ ]:
### Matrix A has shape (3,3) while matrix B has shape(4,4) it is not possible to add these matrices as shapes are different
Below is alternate example to show matrix addition

In [ ]:
matrix1 = tf.random.normal(shape=(2,2))
matrix2 = tf.random.normal(shape=(2,2))
D = tf.add(matrix1, matrix2)
print(f'Matrix 1 :\n {matrix1.numpy()}')
print(f'\nMatrix 2 :\n {matrix2.numpy()}')
print(f'\nMatrix D :\n {D.numpy()}')

Matrix 1 :
 [[-0.6932158   0.05426229]
 [ 0.35234645 -0.10536154]]

Matrix 2 :
 [[-0.37355402 -0.44618416]
 [-0.6125312   1.0581025 ]]

Matrix D :
 [[-1.0667698  -0.39192188]
 [-0.26018474  0.95274097]]


In [ ]:
## Q5. Perform matrix multiplication between  matrix C and matrix D and store result in matrix E
---

In [ ]:
E = tf.matmul(C,D)

print(f'Matrix C :\n{C.numpy()}')
print(f'\nMatrix D :\n{D.numpy()}')
print(f'\nMatrix E = CxD:\n{E.numpy()}')

Matrix C :
[[3.6540046 3.1320784]
 [3.3171096 2.8479006]]

Matrix D :
[[-1.0667698  -0.39192188]
 [-0.26018474  0.95274097]]

Matrix E = CxD:
[[-4.712901   1.551975 ]
 [-4.2795725  1.4132638]]


In [ ]:
# Task 2: Performing additional matrix operations
---

In [ ]:
## Q1. Create a matrix F with dimensions 3x3, initialized random values using Tensorflows random_uniform function.
---

In [ ]:
# Create a matrix F
F = tf.random.uniform(shape=(3,3))
print(f'Matrix F :\n{F.numpy()}')

Matrix F :
[[0.20843422 0.5754608  0.9162878 ]
 [0.53719544 0.5443474  0.21407783]
 [0.14513743 0.10453808 0.21670055]]


In [ ]:
## Q2. Calculate Transpose of Matrix F and store in Matrix G
---

In [ ]:
# Transpose the F matrix
G = tf.transpose(F)

# Print the matrix
print(f'Matrix G :\n{G.numpy()}')

Matrix G :
[[0.20843422 0.53719544 0.14513743]
 [0.5754608  0.5443474  0.10453808]
 [0.9162878  0.21407783 0.21670055]]


In [ ]:
## Q3. Calculate element wise exponential of Matrix F and store the result in matrix H
---

In [ ]:
# Element wise exponent
H = tf.math.exp(F)

# Print matrix H
print(f'Matrix H :\n{H.numpy()}')

Matrix H :
[[1.2317479 1.7779496 2.4999926]
 [1.711201  1.7234833 1.2387191]
 [1.1561985 1.1101977 1.2419721]]


In [ ]:
## Q4. Create a matrix I by concatenating Matrix F and matrix G horizontally
---

In [ ]:
# Concatenate matrices F and G horizontally to create matrix I
I = tf.concat([F, G], axis=1)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix G:")
print(G.numpy())

print("\nMatrix I (Concatenated Horizontally):")
print(I.numpy())

Matrix F:
[[0.20843422 0.5754608  0.9162878 ]
 [0.53719544 0.5443474  0.21407783]
 [0.14513743 0.10453808 0.21670055]]

Matrix G:
[[0.20843422 0.53719544 0.14513743]
 [0.5754608  0.5443474  0.10453808]
 [0.9162878  0.21407783 0.21670055]]

Matrix I (Concatenated Horizontally):
[[0.20843422 0.5754608  0.9162878  0.20843422 0.53719544 0.14513743]
 [0.53719544 0.5443474  0.21407783 0.5754608  0.5443474  0.10453808]
 [0.14513743 0.10453808 0.21670055 0.9162878  0.21407783 0.21670055]]


In [ ]:
## Q5. Create a matrix J by concatenating matrix F and matrix H vertically

In [ ]:
# Concatenate matrices F and H vertically to create matrix J
J = tf.concat([F, H], axis=0)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix H:")
print(H.numpy())

print("\nMatrix J (Concatenated Vertically):")
print(J.numpy())

Matrix F:
[[0.20843422 0.5754608  0.9162878 ]
 [0.53719544 0.5443474  0.21407783]
 [0.14513743 0.10453808 0.21670055]]

Matrix H:
[[1.2317479 1.7779496 2.4999926]
 [1.711201  1.7234833 1.2387191]
 [1.1561985 1.1101977 1.2419721]]

Matrix J (Concatenated Vertically):
[[0.20843422 0.5754608  0.9162878 ]
 [0.53719544 0.5443474  0.21407783]
 [0.14513743 0.10453808 0.21670055]
 [1.2317479  1.7779496  2.4999926 ]
 [1.711201   1.7234833  1.2387191 ]
 [1.1561985  1.1101977  1.2419721 ]]
